datasets:
  organ_aware_report_generation:
    data_type: images
    
    build_info:
      # JSON files for decomposed reports (no CSV needed)
      conc_info_path: /home/muhammedg/test/fvlm/data/conc_info.json
      desc_info_path: /home/muhammedg/test/fvlm/data/desc_info.json
      images:
        storage: /home/muhammedg/fvlm/data/
    
    text_processor:
      train:
        name: "blip_caption"
      eval:
        name: "blip_caption"
